export const ALL_DEVICES_LOADING_START = "ALL_DEVICES_LOADING_START";
export const ALL_DEVICES_GET_SUCCESS = "ALL_DEVICES_GET_SUCCESS";
export const ALL_DEVICES_LOADING_ERROR = "ALL_DEVICES_LOADING_ERROR";
export const ALL_DEVICES_CHANGE_STATUS = "ALL_DEVICES_CHANGE_STATUS";
