export const CURRENT_MARKER_LOADING_START = "CURRENT_MARKER_LOADING_START";
export const CURRENT_MARKER_GET_SUCCESS = "CURRENT_MARKER_GET_SUCCESS";
export const CURRENT_MARKER_LOADING_ERROR = "CURRENT_MARKER_LOADING_ERROR";
export const CURRENT_MARKER_CLEAR = "CURRENT_MARKER_CLEAR";
