export const DEVICES_LOADING_START = "DEVICES_LOADING_START";
export const DEVICES_GET_SUCCESS = "DEVICES_GET_SUCCESS";
export const DEVICES_LOADING_ERROR = "DEVICES_LOADING_ERROR";
export const DEVICES_CHANGE_STATUS = "DEVICES_CHANGE_STATUS";
