export const ROOMS_LOADING_START = "ROOMS_LOADING_START";
export const ROOMS_GET_SUCCESS = "ROOMS_GET_SUCCESS";
export const ROOMS_LOADING_ERROR = "ROOMS_LOADING_ERROR";
export const ROOM_ADD = "ROOM_ADD";

export const ROOM_MARKER_UPDATE = "ROOM_MARKER_UPDATE"
