export const SENSORS_LOADING_START = "SENSORS_LOADING_START";
export const SENSORS_GET_SUCCESS = "SENSORS_GET_SUCCESS";
export const SENSORS_LOADING_ERROR = "SENSORS_LOADING_ERROR";
export const SENSORS_CHANGE_STATUS = "SENSORS_CHANGE_STATUS";
export const SENSORS_CHANGE_VALUE = "SENSORS_CHANGE_VALUE";
